// pSEO data: 80 use-case pages (8 tools x 10) + 2 comparison pages

export interface PseoPage {
  slug: string;
  parentTool: string;
  parentToolKey: string;
  title: string;
  h1: string;
  metaDescription: string;
  keywords: string[];
  intro: string;
  exampleInput: string;
  tips: string[];
  faqs: { q: string; a: string }[];
}

export interface ComparisonPage {
  slug: string;
  title: string;
  h1: string;
  metaDescription: string;
  keywords: string[];
  intro: string;
  sections: { heading: string; content: string }[];
  faqs: { q: string; a: string }[];
}

// Helper: parent tool info
const TOOLS = {
  json: { parentTool: "json-formatter", parentToolKey: "jsonFormatter" },
  base64: { parentTool: "base64-encode-decode", parentToolKey: "base64" },
  url: { parentTool: "url-encode-decode", parentToolKey: "urlEncode" },
  regex: { parentTool: "regex-tester", parentToolKey: "regexTester" },
  diff: { parentTool: "diff-checker", parentToolKey: "diffChecker" },
  jwt: { parentTool: "jwt-decoder", parentToolKey: "jwtDecoder" },
  sql: { parentTool: "sql-formatter", parentToolKey: "sqlFormatter" },
  hash: { parentTool: "hash-generator", parentToolKey: "hashGenerator" },
} as const;

// ─── JSON Formatter (10 pages) ───
const jsonPages: PseoPage[] = [
  { slug: "json-formatter-for-aws-cloudformation", ...TOOLS.json, title: "JSON Formatter for AWS CloudFormation Templates", h1: "JSON Formatter for AWS CloudFormation", metaDescription: "Format and validate AWS CloudFormation JSON templates instantly. Catch syntax errors before deployment. 100% client-side.", keywords: ["cloudformation json formatter", "aws json validator", "cloudformation template formatter", "aws json beautifier"], intro: "AWS CloudFormation templates can grow to thousands of lines. A single misplaced bracket can cause a stack deployment to fail. Validate and beautify your CloudFormation JSON before pushing to AWS, without sending your infrastructure code to any server.", exampleInput: '{\n  "AWSTemplateFormatVersion": "2010-09-09",\n  "Resources": {\n    "WebServer": {\n      "Type": "AWS::EC2::Instance",\n      "Properties": {\n        "InstanceType": "t3.micro",\n        "ImageId": "ami-0c55b159cbfafe1f0"\n      }\n    }\n  }\n}', tips: ["Validate CloudFormation JSON locally before running aws cloudformation validate-template.", "Use tree view to navigate deeply nested Resource properties.", "Convert CloudFormation JSON to YAML using the built-in converter."], faqs: [{ q: "Does formatting change behavior?", a: "No. Formatting only affects whitespace." }, { q: "Can I format large templates?", a: "Yes, up to 5 MB." }, { q: "Is my code safe?", a: "Yes. All formatting happens in your browser." }] },
  { slug: "json-formatter-for-api-response", ...TOOLS.json, title: "JSON Formatter for API Responses \u2014 Pretty Print", h1: "JSON Formatter for API Responses", metaDescription: "Pretty-print API response JSON. Tree view, real-time validation. Privacy-first \u2014 your API data stays local.", keywords: ["api response formatter", "pretty print api json", "json api viewer", "format api response"], intro: "When debugging API integrations, raw JSON responses are often minified. Paste your response to instantly format with tree view. Your API data never leaves your browser.", exampleInput: '{"status":"success","data":{"users":[{"id":1,"name":"Alice","role":"admin"}],"pagination":{"page":1,"total":247}}}', tips: ["Use JSON Path queries like $.data.users[0].name.", "Compare responses using the Diff Checker.", "Minify back to a single line for curl commands."], faqs: [{ q: "Handles special characters?", a: "Yes. All valid JSON including Unicode." }, { q: "Invalid JSON?", a: "Shows real-time validation errors with line numbers." }, { q: "Data safe?", a: "Yes. No data sent to any server." }] },
  { slug: "json-formatter-for-package-json", ...TOOLS.json, title: "JSON Formatter for package.json", h1: "JSON Formatter for package.json", metaDescription: "Format and validate package.json. Catch missing commas and structural errors. Runs in your browser.", keywords: ["package.json formatter", "validate package json", "npm json validator"], intro: "A broken package.json stops npm install dead. Format and validate to catch syntax issues before committing.", exampleInput: '{\n  "name": "my-app",\n  "scripts": {"dev": "next dev", "build": "next build"},\n  "dependencies": {"next": "^16.0.0", "react": "^19.0.0"}\n}', tips: ["Use 2-space indentation (npm default).", "Validate after merge conflicts.", "Tree view for nested config sections."], faqs: [{ q: "Why does npm install fail?", a: "Usually a missing comma or mismatched quotes. Paste here to see the error." }, { q: "Sort dependencies?", a: "Format first, then sort dependency blocks in editor." }, { q: "Validates npm rules?", a: "JSON syntax only. Use npm pkg fix for npm-specific validation." }] },
  { slug: "json-formatter-for-terraform", ...TOOLS.json, title: "JSON Formatter for Terraform tfstate & Config", h1: "JSON Formatter for Terraform", metaDescription: "Format Terraform state files. Navigate infrastructure state with tree view. Client-side \u2014 secrets stay local.", keywords: ["terraform json formatter", "format tfstate", "terraform state viewer"], intro: "Terraform state files contain secrets and resource IDs. Never paste them into tools that send data to servers. CodeNeat processes everything locally.", exampleInput: '{"version": 4, "terraform_version": "1.9.0", "resources": [{"type": "aws_instance", "name": "web", "instances": [{"attributes": {"id": "i-0abc123", "instance_type": "t3.medium"}}]}]}', tips: ["Use tree view for large state files.", "Never share tfstate without redacting secrets.", "JSON only \u2014 use terraform fmt for HCL."], faqs: [{ q: "Safe for tfstate?", a: "Yes. Everything processed in your browser." }, { q: "Max size?", a: "Up to 5 MB." }, { q: "Convert to HCL?", a: "Not supported. Use terraform fmt." }] },
  { slug: "json-formatter-for-mongodb", ...TOOLS.json, title: "JSON Formatter for MongoDB Documents", h1: "JSON Formatter for MongoDB", metaDescription: "Format MongoDB documents and aggregation pipelines. Client-side \u2014 database data stays private.", keywords: ["mongodb json formatter", "format mongodb query", "mongodb document viewer"], intro: "Format complex aggregation pipelines and documents locally without exposing database contents.", exampleInput: '{"_id": {"$oid": "661f2a3b4c5d6e7f"}, "username": "dev42", "profile": {"skills": ["TypeScript", "React"]}, "loginCount": 847}', tips: ["Tree view for nested documents.", "Extended JSON ($oid, $date) formats correctly.", "Copy pipeline stages individually."], faqs: [{ q: "Extended JSON?", a: "Yes. $oid, $date, $regex are standard JSON." }, { q: "Aggregation pipelines?", a: "Yes. Tree view helps with complex stages." }, { q: "Data safe?", a: "Yes. All in browser." }] },
  { slug: "json-formatter-for-elasticsearch", ...TOOLS.json, title: "JSON Formatter for Elasticsearch Queries", h1: "JSON Formatter for Elasticsearch", metaDescription: "Format Elasticsearch queries and mappings. Navigate complex DSL. Privacy-first.", keywords: ["elasticsearch json formatter", "elastic dsl formatter", "format elasticsearch query"], intro: "Elasticsearch Query DSL can be deeply nested. Format to catch structural errors.", exampleInput: '{"query": {"bool": {"must": [{"match": {"title": "developer tools"}}], "filter": [{"term": {"status": "published"}}]}}, "size": 20}', tips: ["Format bool queries to verify clause nesting.", "Tree view to collapse sections.", "Validate before sending to cluster."], faqs: [{ q: "Works with OpenSearch?", a: "Yes. Same JSON DSL." }, { q: "Format mappings?", a: "Yes. JSON formats perfectly." }, { q: "Data safe?", a: "Yes." }] },
  { slug: "json-formatter-for-graphql-response", ...TOOLS.json, title: "JSON Formatter for GraphQL Responses", h1: "JSON Formatter for GraphQL Responses", metaDescription: "Format GraphQL API response JSON. Navigate nested data with tree view. Client-side.", keywords: ["graphql json formatter", "graphql result viewer", "format graphql response"], intro: "GraphQL responses mirror query structure. Format to trace data paths.", exampleInput: '{"data": {"user": {"id": "usr_k8x2m", "posts": {"edges": [{"node": {"title": "Getting Started"}}], "pageInfo": {"hasNextPage": true}}}}}', tips: ["Tree view traces root to leaf.", "Check errors array for partial failures.", "JSON Path for nested fields."], faqs: [{ q: "See errors?", a: "Yes. Format full response including errors." }, { q: "Relay pagination?", a: "Tree view expands edges and pageInfo." }, { q: "Subscriptions?", a: "Yes, if captured as JSON." }] },
  { slug: "json-formatter-for-swagger-openapi", ...TOOLS.json, title: "JSON Formatter for Swagger / OpenAPI", h1: "JSON Formatter for Swagger & OpenAPI", metaDescription: "Format OpenAPI/Swagger JSON specs. Navigate API definitions. 100% local.", keywords: ["swagger json formatter", "openapi formatter", "api spec formatter"], intro: "OpenAPI specs define your API surface. Format and navigate without uploading to third parties.", exampleInput: '{"openapi": "3.1.0", "info": {"title": "User API", "version": "2.0"}, "paths": {"/users": {"get": {"summary": "List users"}}}}', tips: ["Tree view for paths, schemas, security.", "Convert to YAML with built-in converter.", "Validate syntax before OpenAPI linters."], faqs: [{ q: "Convert to YAML?", a: "Yes. JSON to YAML button." }, { q: "OpenAPI validation?", a: "JSON structure only. Use Spectral for spec rules." }, { q: "Individual endpoints?", a: "Yes. Any JSON fragment works." }] },
  { slug: "json-formatter-for-firebase-config", ...TOOLS.json, title: "JSON Formatter for Firebase Configuration", h1: "JSON Formatter for Firebase Config", metaDescription: "Format Firebase config files. Client-side \u2014 Firebase secrets stay private.", keywords: ["firebase json formatter", "format firebase config", "firestore json viewer"], intro: "Firebase configs contain project IDs and API keys. Format locally.", exampleInput: '{"projects": {"default": "my-app"}, "hosting": {"public": "dist", "rewrites": [{"source": "/api/**", "function": "api"}]}}', tips: ["Validate firebase.json before deploy.", "Tree view for rewrite rules.", "Format Realtime Database exports."], faqs: [{ q: "Firestore exports?", a: "Yes. Standard JSON." }, { q: "Safe?", a: "Yes. Browser only." }, { q: "Database rules?", a: "If JSON format, yes." }] },
  { slug: "json-formatter-for-kubernetes-manifest", ...TOOLS.json, title: "JSON Formatter for Kubernetes Manifests", h1: "JSON Formatter for Kubernetes", metaDescription: "Format K8s JSON manifests. Inspect deployments, services, configmaps. Privacy-first.", keywords: ["kubernetes json formatter", "k8s manifest formatter", "kubectl json viewer"], intro: "Format K8s manifests to verify structure before applying to your cluster.", exampleInput: '{"apiVersion": "apps/v1", "kind": "Deployment", "metadata": {"name": "web-app"}, "spec": {"replicas": 3, "template": {"spec": {"containers": [{"name": "web", "image": "node:22", "ports": [{"containerPort": 8080}]}]}}}}', tips: ["Format kubectl -o json output.", "Tree view for resource limits.", "Convert to YAML with converter."], faqs: [{ q: "kubectl output?", a: "Yes. Paste directly." }, { q: "Multi-document?", a: "Convert each YAML doc separately." }, { q: "Helm values?", a: "JSON format only. Use YAML converter." }] },
];

// ─── Base64 (10 pages) ───
const base64Pages: PseoPage[] = [
  { slug: "base64-encoder-for-images", ...TOOLS.base64, title: "Base64 Encoder for Images \u2014 Data URLs", h1: "Base64 Encoder for Images", metaDescription: "Convert images to Base64 data URLs for HTML/CSS. 100% local.", keywords: ["base64 image encoder", "image to base64", "data url encoder"], intro: "Embed images as Base64 data URLs to eliminate HTTP requests. Useful for icons and email templates.", exampleInput: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUg...", tips: ["Keep under 10KB.", "Prefix: data:image/png;base64,", "SVGs can be URL-encoded instead."], faqs: [{ q: "Increases size?", a: "Yes, ~33%. Only encode small images." }, { q: "Decode back?", a: "Yes." }, { q: "Why encode?", a: "Embed in HTML/CSS without extra HTTP requests." }] },
  { slug: "base64-decoder-for-jwt-tokens", ...TOOLS.base64, title: "Base64 Decoder for JWT Tokens", h1: "Base64 Decoder for JWT Tokens", metaDescription: "Decode JWT segments using Base64. Inspect headers and payloads. Client-side.", keywords: ["decode jwt base64", "jwt payload decoder", "base64url decoder"], intro: "JWT tokens have three Base64URL-encoded segments. Decode to inspect claims locally.", exampleInput: "[Paste a JWT token segment \u2014 the part between the dots \u2014 to decode its content]", tips: ["JWT uses Base64URL (- and _ instead of + and /).", "Decode first two segments only.", "Use JWT Decoder for full inspection."], faqs: [{ q: "Base64 vs Base64URL?", a: "Base64URL replaces + with - and / with _ for URL safety." }, { q: "Send tokens to decoders?", a: "No. Always decode locally." }, { q: "Decode signature?", a: "Possible but it's binary data." }] },
  { slug: "base64-encode-for-api-authentication", ...TOOLS.base64, title: "Base64 Encoder for API Authentication", h1: "Base64 Encoder for API Auth", metaDescription: "Encode credentials for HTTP Basic Auth. Client-side \u2014 credentials stay private.", keywords: ["base64 basic auth", "encode api credentials", "http basic authentication"], intro: "HTTP Basic Auth requires Base64-encoded username:password. Encode in your browser.", exampleInput: "api_user:your_api_key_here", tips: ["Format: username:password.", "Header: Authorization: Basic <encoded>.", "Never commit encoded credentials."], faqs: [{ q: "Same as encryption?", a: "No. Anyone can decode. Use HTTPS." }, { q: "curl usage?", a: "curl -H 'Authorization: Basic <encoded>' URL" }, { q: "Why this tool?", a: "No terminal needed." }] },
  { slug: "base64-decode-for-email-headers", ...TOOLS.base64, title: "Base64 Decoder for Email Headers", h1: "Base64 Decoder for Email Headers", metaDescription: "Decode MIME Base64 email headers. Client-side \u2014 emails stay private.", keywords: ["decode email base64", "mime base64 decoder", "email header decoder"], intro: "Email headers with non-ASCII characters use Base64 (RFC 2047). Decode locally.", exampleInput: "=?UTF-8?B?5oKo44Gu5rOo5paH44GM56K65a6a44GV44KM44G+44GX44Gf?=", tips: ["Format: =?charset?B?data?=", "Q encoding is different.", "Decode segments individually."], faqs: [{ q: "What is =?UTF-8?B?...?=?", a: "MIME encoded word: charset, Base64 encoding, content." }, { q: "Decode attachments?", a: "Yes. Extract Base64 block and decode." }, { q: "Why encoded?", a: "SMTP is ASCII-only. Non-ASCII must be encoded." }] },
  { slug: "base64-encoder-for-data-urls", ...TOOLS.base64, title: "Base64 Encoder for Data URLs", h1: "Base64 Encoder for Data URLs", metaDescription: "Create data URLs for inline HTML/CSS resources. Zero server requests.", keywords: ["data url encoder", "base64 data url", "inline resource"], intro: "Data URLs embed content directly in HTML/CSS using data:[type];base64, scheme.", exampleInput: "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\"><path d=\"M12 2L2 7l10 5z\"/></svg>", tips: ["Prefix: data:image/svg+xml;base64,", "Only inline small resources.", "Modern bundlers auto-inline."], faqs: [{ q: "When to use?", a: "Small resources, email templates." }, { q: "Browser support?", a: "All modern browsers." }, { q: "In CSS?", a: "Yes. background-image: url(data:...)." }] },
  { slug: "base64-decode-for-certificates", ...TOOLS.base64, title: "Base64 Decoder for SSL Certificates", h1: "Base64 Decoder for Certificates", metaDescription: "Decode PEM certificates. Never upload private keys to external tools. Client-side.", keywords: ["decode pem", "ssl certificate decoder", "pem decoder"], intro: "PEM certificates are Base64-encoded. Decode locally \u2014 especially private keys.", exampleInput: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA...", tips: ["Strip BEGIN/END markers.", "Output is binary ASN.1.", "Never share private keys."], faqs: [{ q: "Safe for private keys?", a: "Yes. Browser only." }, { q: "What is PEM?", a: "Base64 + BEGIN/END markers." }, { q: "See cert details?", a: "Use openssl x509 for readable output." }] },
  { slug: "base64-encode-for-basic-auth", ...TOOLS.base64, title: "Base64 Encoder for Basic Auth Headers", h1: "Base64 Encoder for Basic Auth", metaDescription: "Generate Base64 Authorization headers. Encode safely in browser.", keywords: ["basic auth encoder", "authorization header", "encode basic auth"], intro: "Generate Base64 for Authorization: Basic headers without exposing credentials.", exampleInput: "admin:SecurePassword123!", tips: ["Full header: Authorization: Basic <result>.", "Test with curl.", "Always use HTTPS."], faqs: [{ q: "Secure?", a: "Only over HTTPS." }, { q: "Production?", a: "OK for server-to-server. Use OAuth for users." }, { q: "Special chars?", a: "Yes. Colon separates user:pass." }] },
  { slug: "base64-decoder-for-binary-data", ...TOOLS.base64, title: "Base64 Decoder for Binary Data", h1: "Base64 Decoder for Binary Data", metaDescription: "Decode Base64 binary data to text or files. Client-side.", keywords: ["base64 binary decoder", "decode base64 file", "base64 to binary"], intro: "APIs often Base64-encode binary data for JSON transport. Decode locally.", exampleInput: "[Paste Base64-encoded binary data from API responses]", tips: ["Garbled output = binary. Download as file.", "Common: PDFs, images, protobuf.", "Check for = padding."], faqs: [{ q: "Text or binary?", a: "Readable = text. Garbled = binary file." }, { q: "Max size?", a: "Several MB. Use command-line for larger." }, { q: "From JSON?", a: "Extract Base64 string (no quotes) and paste." }] },
  { slug: "base64-encode-for-xml-payloads", ...TOOLS.base64, title: "Base64 Encoder for XML \u2014 SOAP & SAML", h1: "Base64 Encoder for XML Payloads", metaDescription: "Encode XML for SOAP and SAML. Client-side \u2014 XML data stays private.", keywords: ["base64 xml encoder", "saml base64", "soap payload encoder"], intro: "SOAP and SAML require Base64-encoded XML. Especially important for SAML auth assertions.", exampleInput: "<saml:Assertion><saml:Issuer>https://idp.example.com</saml:Issuer></saml:Assertion>", tips: ["SAML responses contain Base64 assertions.", "No extra whitespace before encoding.", "SOAP MTOM uses Base64."], faqs: [{ q: "Why Base64 for SAML?", a: "Assertions travel via HTTP POST form parameters." }, { q: "Decode SAML?", a: "Yes. Paste SAMLResponse value." }, { q: "Different from text?", a: "No. Base64 treats all input as bytes." }] },
  { slug: "base64-encode-for-svg-embedding", ...TOOLS.base64, title: "Base64 Encoder for SVG Embedding", h1: "Base64 Encoder for SVG", metaDescription: "Convert SVG to Base64 for CSS and HTML embedding. No server needed.", keywords: ["svg base64 encoder", "embed svg base64", "svg data url"], intro: "Embed SVG icons as Base64 data URLs in CSS to eliminate icon HTTP requests.", exampleInput: "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" stroke=\"#059669\"><polyline points=\"20 6 9 17 4 12\"/></svg>", tips: ["CSS: background-image: url('data:image/svg+xml;base64,...').", "URL-encoding often smaller for SVGs.", "Minify SVG first."], faqs: [{ q: "Base64 or URL-encode?", a: "URL-encoding usually smaller. Base64 for compatibility." }, { q: "Animated SVGs?", a: "Yes, preserved." }, { q: "Max size?", a: "Keep under 10KB for performance." }] },
];

// ─── URL Encode/Decode (10 pages) ───
const urlPages: PseoPage[] = [
  { slug: "url-encoder-for-query-parameters", ...TOOLS.url, title: "URL Encoder for Query Parameters", h1: "URL Encoder for Query Parameters", metaDescription: "Encode query parameter values. Handle spaces, ampersands, Unicode. Client-side.", keywords: ["url encode query", "encode special characters", "query string encoder"], intro: "Query parameters with &, =, # and spaces must be encoded to avoid breaking URL parsing.", exampleInput: "search=hello world&category=dev tools&filter=price<50", tips: ["Encode values only.", "Spaces: %20 (standard) or + (form).", "Test in browser first."], faqs: [{ q: "Entire URL or values?", a: "Just values." }, { q: "encodeURI vs encodeURIComponent?", a: "encodeURI preserves structure. encodeURIComponent encodes everything." }, { q: "Spaces?", a: "%20 standard, + in forms." }] },
  { slug: "url-decoder-for-encoded-links", ...TOOLS.url, title: "URL Decoder \u2014 Decode Percent-Encoded Links", h1: "URL Decoder for Encoded Links", metaDescription: "Decode percent-encoded URLs to readable text. Client-side.", keywords: ["url decoder", "decode percent encoding", "decode encoded url"], intro: "URLs from analytics and tracking are heavily encoded. Decode to readable text.", exampleInput: "https%3A%2F%2Fexample.com%2Fsearch%3Fq%3Dhello%2520world", tips: ["Double-encoded: decode twice.", "Look for utm_ parameters.", "May reveal redirect destinations."], faqs: [{ q: "%20?", a: "Space. %3A = colon, %2F = slash." }, { q: "Multiple encodings?", a: "Each redirect system encodes again." }, { q: "Non-Latin?", a: "Unicode decodes correctly from UTF-8." }] },
  { slug: "url-encode-for-special-characters", ...TOOLS.url, title: "URL Encoder for Special Characters", h1: "URL Encoder for Special Characters", metaDescription: "Encode &, #, ?, = for URLs. Prevent parsing errors. Client-side.", keywords: ["encode ampersand url", "encode hash url", "url special characters"], intro: "Characters with special URL meaning must be percent-encoded in data values.", exampleInput: "file name (v2.1) #draft \u2014 final & approved.pdf", tips: ["# becomes fragment identifier if not encoded.", "& is parameter separator.", "? starts query string."], faqs: [{ q: "Which chars?", a: "Reserved: :/?#[]@!$&'()*+,;= and non-ASCII." }, { q: "# breaks URL?", a: "Browser treats after # as fragment. Encode as %23." }, { q: "Encode full URL?", a: "Use Full URL mode to preserve structure." }] },
  { slug: "url-encode-for-api-requests", ...TOOLS.url, title: "URL Encoder for API Requests", h1: "URL Encoder for API Requests", metaDescription: "Encode API request parameters. Build valid REST URLs. Client-side.", keywords: ["url encode api", "encode api parameters", "rest api encoder"], intro: "REST API parameters with special characters need encoding to prevent 400 errors.", exampleInput: "filter=status:active AND created>2026-01-01&search=user@example.com", tips: ["Encode each value separately.", "Check if API expects + or %20.", "Test with curl -v."], faqs: [{ q: "Encode API keys?", a: "If special chars, yes. But prefer headers." }, { q: "400 errors?", a: "Unencoded & and = break the parser." }, { q: "JSON bodies?", a: "No URL encoding needed." }] },
  { slug: "url-decoder-for-tracking-links", ...TOOLS.url, title: "URL Decoder for Tracking Links", h1: "URL Decoder for Tracking Links", metaDescription: "Decode tracking URLs. Reveal destinations and UTM params. Client-side.", keywords: ["decode tracking url", "decode utm parameters", "marketing url decoder"], intro: "Marketing emails wrap URLs in tracking redirects. Decode to see actual destinations.", exampleInput: "https://track.example.com/click?url=https%3A%2F%2Fcodeneat.dev%3Futm_source%3Dnewsletter", tips: ["Decode repeatedly for multi-layer.", "Look for utm_ parameters.", "Check for hidden user IDs."], faqs: [{ q: "Why encoded?", a: "Destination embedded as parameter." }, { q: "Personal info?", a: "User IDs and email hashes are common." }, { q: "Remove tracking?", a: "Remove utm_*, fbclid, gclid." }] },
  { slug: "url-encode-for-redirect-urls", ...TOOLS.url, title: "URL Encoder for Redirect URLs", h1: "URL Encoder for Redirect URLs", metaDescription: "Encode redirect and callback URLs for OAuth. Client-side.", keywords: ["encode redirect url", "oauth redirect encoder", "encode callback"], intro: "Redirect URLs as parameters must be fully encoded.", exampleInput: "https://myapp.com/auth/callback?code=abc&state=xyz", tips: ["Encode entire redirect URL.", "Must match OAuth allowed callbacks.", "Test in staging."], faqs: [{ q: "invalid_redirect_uri?", a: "Check trailing slashes, protocol, port." }, { q: "Double encode?", a: "Usually once." }, { q: "Localhost?", a: "Yes. Encode same way." }] },
  { slug: "url-encode-for-form-data", ...TOOLS.url, title: "URL Encoder for Form Data", h1: "URL Encoder for Form Data", metaDescription: "Encode form values for x-www-form-urlencoded. Client-side.", keywords: ["form urlencoded encoder", "encode form values", "form data encoder"], intro: "HTML forms send data as application/x-www-form-urlencoded. Special characters need encoding.", exampleInput: "username=alice@example.com&message=Budget & timeline discussion", tips: ["Form encoding uses + for spaces.", "Applies to POST bodies.", "Libraries handle automatically."], faqs: [{ q: "Form vs URL encoding?", a: "Form uses + for spaces." }, { q: "When manual?", a: "Raw HTTP or curl testing." }, { q: "Files?", a: "Use multipart/form-data instead." }] },
  { slug: "url-encode-for-oauth-callbacks", ...TOOLS.url, title: "URL Encoder for OAuth Callbacks", h1: "URL Encoder for OAuth Callbacks", metaDescription: "Encode OAuth redirect_uri. Prevent auth errors. Client-side.", keywords: ["oauth url encoder", "encode redirect uri", "oauth callback encoder"], intro: "OAuth redirect_uri must be exactly encoded. One wrong character causes rejection.", exampleInput: "https://myapp.com/auth/callback?provider=google", tips: ["Must match registered URLs exactly.", "Encode full URL including params.", "Same encoding in both requests."], faqs: [{ q: "invalid_redirect_uri?", a: "Check exact match." }, { q: "Encode state?", a: "Yes, if special characters." }, { q: "Wildcards?", a: "Most providers don't support." }] },
  { slug: "url-encode-for-email-links", ...TOOLS.url, title: "URL Encoder for mailto Links", h1: "URL Encoder for Email Links", metaDescription: "Encode mailto link subject and body. Handle special characters. Client-side.", keywords: ["mailto encoder", "encode email link", "mailto subject encoder"], intro: "Mailto links need URL encoding for special characters and line breaks.", exampleInput: "subject=Question about pricing & features&body=Hi, I'd like to learn more.", tips: ["Line breaks: %0A.", "Format: mailto:user@example.com?subject=&body=.", "Test in multiple clients."], faqs: [{ q: "Line breaks?", a: "Encode as %0A." }, { q: "Length limit?", a: "~2000 chars total." }, { q: "HTML in body?", a: "No. Plain text only." }] },
  { slug: "url-encode-for-unicode-text", ...TOOLS.url, title: "URL Encoder for Unicode Text", h1: "URL Encoder for Unicode Text", metaDescription: "Encode CJK, emoji, and accented characters for URLs. Client-side.", keywords: ["unicode url encoder", "encode chinese url", "url encode emoji"], intro: "Non-ASCII characters must be encoded as UTF-8 byte sequences for URLs.", exampleInput: "search=\u5f00\u53d1\u5de5\u5177&lang=\u4e2d\u6587&name=Jos\u00e9 Garc\u00eda", tips: ["Chinese: 3 bytes each.", "Emoji: 4 bytes each.", "Browsers encode automatically but code needs manual."], faqs: [{ q: "Chinese in URLs?", a: "\u4e2d = %E4%B8%AD (3 bytes)." }, { q: "Automatic?", a: "Display yes, sending yes. Manual encoding needed in code." }, { q: "Domain names?", a: "Use Punycode, not percent encoding." }] },
];

// ─── Regex Tester (10 pages) ───
const regexPages: PseoPage[] = [
  { slug: "regex-tester-for-email-validation", ...TOOLS.regex, title: "Regex Tester for Email Validation", h1: "Regex Tester for Email Validation", metaDescription: "Test email validation regex. Real-time matching. Client-side \u2014 test data stays private.", keywords: ["email regex tester", "validate email regex", "email pattern"], intro: "Email validation is tricky. Test against edge cases like subdomains, plus addressing, and international domains.", exampleInput: "Pattern: ^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\\\.[a-zA-Z]{2,}$\\n\\nTest: alice@example.com, bob+tag@sub.domain.co.uk, invalid@", tips: ["No regex fully validates per RFC 5322.", "Allow + addressing.", "Test international addresses."], faqs: [{ q: "Best email regex?", a: "Practical: ^[^\\\\s@]+@[^\\\\s@]+\\\\.[^\\\\s@]+$" }, { q: "Regex or library?", a: "Regex for format check. Library + verification email for production." }, { q: "International?", a: "Broader character ranges needed." }] },
  { slug: "regex-tester-for-phone-numbers", ...TOOLS.regex, title: "Regex Tester for Phone Numbers", h1: "Regex Tester for Phone Numbers", metaDescription: "Test phone number regex for international formats. Client-side.", keywords: ["phone number regex", "validate phone regex", "international phone"], intro: "Phone numbers come in dozens of formats. Test your regex against various international formats.", exampleInput: "Pattern: ^\\\\+?[1-9]\\\\d{1,14}$\\n\\nTest: +1-555-123-4567, +82-10-1234-5678", tips: ["Use E.164 for storage.", "Capture groups for parts.", "Use libphonenumber for display."], faqs: [{ q: "Simplest?", a: "^\\\\+?\\\\d{7,15}$" }, { q: "Strip formatting?", a: "Yes. Remove spaces/dashes/parens first." }, { q: "US numbers?", a: "^\\\\(?\\\\d{3}\\\\)?[-.\\\\s]?\\\\d{3}[-.\\\\s]?\\\\d{4}$" }] },
  { slug: "regex-tester-for-ip-addresses", ...TOOLS.regex, title: "Regex Tester for IP Addresses", h1: "Regex Tester for IP Addresses", metaDescription: "Test IPv4/IPv6 regex. Match CIDR notation. Client-side.", keywords: ["ip address regex", "ipv4 regex", "ipv6 regex pattern"], intro: "IP validation requires careful regex to reject 999.999.999.999.", exampleInput: "Pattern: ^(?:(?:25[0-5]|2[0-4]\\\\d|[01]?\\\\d\\\\d?)\\\\.){3}(?:25[0-5]|2[0-4]\\\\d|[01]?\\\\d\\\\d?)$\\n\\nTest: 192.168.1.1, 256.1.1.1", tips: ["Simple \\\\d{1,3} matches invalid 999.", "Each octet: 0-255.", "IPv6 is much more complex."], faqs: [{ q: "Validate 0-255?", a: "Yes: (25[0-5]|2[0-4]\\\\d|[01]?\\\\d\\\\d?)" }, { q: "CIDR?", a: "Append \\\\/(3[0-2]|[12]?\\\\d)" }, { q: "Production?", a: "Use IP parsing library." }] },
  { slug: "regex-tester-for-url-validation", ...TOOLS.regex, title: "Regex Tester for URL Validation", h1: "Regex Tester for URL Validation", metaDescription: "Test URL regex for HTTP/HTTPS. Client-side.", keywords: ["url regex tester", "validate url regex", "http url pattern"], intro: "URL validation is deceptively complex. Test against edge cases.", exampleInput: "Pattern: ^https?://[\\\\w.-]+(?:/[\\\\w./-]*)?$\\n\\nTest: https://example.com, not-a-url", tips: ["RFC 3986 is very permissive.", "Use new URL() for reliable JS validation.", "Capture groups for parts."], faqs: [{ q: "Best URL regex?", a: "^https?://[^\\\\s]+$ for practical use." }, { q: "Regex or URL API?", a: "URL API for production." }, { q: "Non-ASCII?", a: "Match broader ranges." }] },
  { slug: "regex-tester-for-date-formats", ...TOOLS.regex, title: "Regex Tester for Date Formats", h1: "Regex Tester for Date Formats", metaDescription: "Test date regex for ISO 8601, US, EU patterns. Client-side.", keywords: ["date regex tester", "iso 8601 regex", "date format regex"], intro: "Date strings vary by locale. Test ISO 8601, US, and European patterns.", exampleInput: "Pattern: ^(\\\\d{4})-(0[1-9]|1[0-2])-(0[1-9]|[12]\\\\d|3[01])$\\n\\nTest: 2026-04-13, 2026-13-01", tips: ["Format only, not logic. 2026-02-30 matches.", "Named groups for readability.", "Append T for time."], faqs: [{ q: "Validate real dates?", a: "Format/ranges only. Use Date.parse() for logic." }, { q: "ISO 8601?", a: "\\\\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12]\\\\d|3[01])" }, { q: "Multiple formats?", a: "Use alternation: (ISO)|(US)|(EU)" }] },
  { slug: "regex-tester-for-password-strength", ...TOOLS.regex, title: "Regex Tester for Password Strength", h1: "Regex Tester for Password Strength", metaDescription: "Test password validation regex. Client-side \u2014 passwords stay private.", keywords: ["password regex", "password strength regex", "validate password"], intro: "Test password rules. Everything runs in your browser \u2014 critical for sensitive data.", exampleInput: "Pattern: ^(?=.*[a-z])(?=.*[A-Z])(?=.*\\\\d)(?=.*[@$!%*?&])[A-Za-z\\\\d@$!%*?&]{8,}$\\n\\nTest: P@ssw0rd!, weak", tips: ["Lookaheads for character types.", "NIST recommends length over complexity.", "Allow long passphrases."], faqs: [{ q: "Good regex?", a: "Min 8 + lookaheads. Favor length." }, { q: "Enough?", a: "Also check breached-password databases." }, { q: "Safe here?", a: "Yes. 100% browser-side." }] },
  { slug: "regex-tester-for-html-tags", ...TOOLS.regex, title: "Regex Tester for HTML Tags", h1: "Regex Tester for HTML Tags", metaDescription: "Test regex for HTML tags and attributes. Client-side.", keywords: ["html tag regex", "match html regex", "extract html"], intro: "Regex for quick HTML extraction. Use a proper parser for production.", exampleInput: "Pattern: <(\\\\w+)[^>]*>([\\\\s\\\\S]*?)<\\\\/\\\\1>\\n\\nTest: <div class=\\\"x\\\">Hello</div>", tips: ["[\\\\s\\\\S]*? for multi-line content.", "\\\\1 backreferences tag name.", "HTML isn't regular \u2014 parser for complex cases."], faqs: [{ q: "Parse HTML?", a: "Quick extraction only. Use DOMParser for production." }, { q: "Self-closing?", a: "<\\\\w+[^>]*/?>  for both <img/> and <img>." }, { q: "Nested?", a: "Regex can't handle recursion." }] },
  { slug: "regex-tester-for-credit-card-numbers", ...TOOLS.regex, title: "Regex Tester for Credit Card Numbers", h1: "Regex Tester for Credit Card Numbers", metaDescription: "Test card number regex. Client-side \u2014 numbers stay private.", keywords: ["credit card regex", "validate card number", "visa regex"], intro: "Sensitive data that should never leave your browser. Test format patterns for card types.", exampleInput: "Pattern: ^4[0-9]{12}(?:[0-9]{3})?$\\n\\nTest: 4111111111111111 (Visa test)", tips: ["Visa: 4xxx. MC: 51-55xx.", "Always Luhn-validate after regex.", "Use test card numbers only."], faqs: [{ q: "Complete validation?", a: "Regex = format. Luhn = checksum." }, { q: "Safe?", a: "Yes. Browser-only. Use test numbers." }, { q: "All card types?", a: "Alternation for each prefix pattern." }] },
  { slug: "regex-tester-for-log-parsing", ...TOOLS.regex, title: "Regex Tester for Log Parsing", h1: "Regex Tester for Log Parsing", metaDescription: "Test regex for server logs. Extract timestamps, IPs, status codes. Client-side.", keywords: ["log parsing regex", "access log regex", "parse server log"], intro: "Log files follow specific formats regex can parse. Test against real log lines.", exampleInput: "Pattern: ^(\\\\S+) .* \\\\[(.*?)\\\\] \\\"(\\\\w+) (\\\\S+)\\\" (\\\\d{3})\\n\\n192.168.1.42 - [13/Apr/2026:10:30] \\\"GET /api\\\" 200", tips: ["Named groups for readability.", "Test edge cases.", "Log parsers for production."], faqs: [{ q: "Apache format?", a: "Well-known pattern with 11 capture groups." }, { q: "Multiline?", a: "Enable multiline flag." }, { q: "Regex or tool?", a: "Regex for analysis. Logstash for production." }] },
  { slug: "regex-tester-for-csv-parsing", ...TOOLS.regex, title: "Regex Tester for CSV Parsing", h1: "Regex Tester for CSV Parsing", metaDescription: "Test regex for CSV with quoted fields. Client-side.", keywords: ["csv regex parser", "parse csv regex", "quoted csv regex"], intro: "CSV with quoted fields and commas is tricky. Test patterns against edge cases.", exampleInput: "Test: Alice,30,\\\"New York, NY\\\",plain value", tips: ["Quoted fields with commas aren't truly regular.", "Escaped quotes: doubled \\\"\\\".", "Use Papa Parse for production."], faqs: [{ q: "Regex for CSV?", a: "Simple CSVs yes. Library for RFC 4180." }, { q: "Commas in quotes?", a: "Match quoted fields first." }, { q: "Library?", a: "Papa Parse handles all edge cases." }] },
];

// ─── Diff Checker (10 pages) ───
const diffPages: PseoPage[] = [
  { slug: "diff-checker-for-json-files", ...TOOLS.diff, title: "Diff Checker for JSON Files", h1: "Diff Checker for JSON Files", metaDescription: "Compare JSON files side by side. Client-side \u2014 data stays private.", keywords: ["json diff checker", "compare json files", "json comparison"], intro: "Compare JSON configs, API responses, or exports with highlighted differences.", exampleInput: "Left: {\\\"version\\\": \\\"1.0\\\"} Right: {\\\"version\\\": \\\"2.0\\\", \\\"cache\\\": true}", tips: ["Format both JSONs first.", "Compare prod vs staging.", "Up to 5000 lines."], faqs: [{ q: "Semantic?", a: "Text-based. Sort keys first for semantic." }, { q: "Large files?", a: "5000 lines per side." }, { q: "Safe?", a: "Yes. All in browser." }] },
  { slug: "diff-checker-for-sql-queries", ...TOOLS.diff, title: "Diff Checker for SQL Queries", h1: "Diff Checker for SQL Queries", metaDescription: "Compare SQL versions side by side. Client-side.", keywords: ["sql diff checker", "compare sql queries"], intro: "See exactly what changed in WHERE, JOINs, and columns.", exampleInput: "Left: SELECT name FROM users WHERE active = true;\\nRight: SELECT name, role FROM users WHERE active = true AND role != 'guest';", tips: ["Format both first.", "Compare execution plans.", "Review migrations."], faqs: [{ q: "Stored procedures?", a: "Yes." }, { q: "SQL-aware?", a: "Text-based. Format first." }, { q: "Any dialect?", a: "Yes." }] },
  { slug: "diff-checker-for-config-files", ...TOOLS.diff, title: "Diff Checker for Config Files", h1: "Diff Checker for Config Files", metaDescription: "Compare configs between environments. Privacy-first.", keywords: ["config diff", "compare config", "env diff"], intro: "Config differences between environments are a top source of bugs.", exampleInput: "Left: DB=localhost\\nDEBUG=true\\n\\nRight: DB=prod.internal\\nDEBUG=false\\nSENTRY=...", tips: ["Compare .env files.", "Sort keys first.", "Check connection strings."], faqs: [{ q: "Safe for .env?", a: "Yes. Browser only." }, { q: "YAML?", a: "Yes. Any text format." }, { q: "Different servers?", a: "Copy from each, paste." }] },
  { slug: "diff-checker-for-api-responses", ...TOOLS.diff, title: "Diff Checker for API Responses", h1: "Diff Checker for API Responses", metaDescription: "Compare API responses between versions. Client-side.", keywords: ["api response diff", "compare api responses"], intro: "Find data discrepancies between environments or versions.", exampleInput: "Left: {\\\"user\\\": {\\\"name\\\": \\\"Alice\\\"}}\\nRight: {\\\"user\\\": {\\\"name\\\": \\\"Alice\\\", \\\"role\\\": \\\"admin\\\"}}", tips: ["Format first.", "Compare staging vs prod.", "Save baselines."], faqs: [{ q: "XML?", a: "Yes. Any text." }, { q: "Dynamic fields?", a: "Remove timestamps first." }, { q: "Safe?", a: "Yes." }] },
  { slug: "diff-checker-for-csv-data", ...TOOLS.diff, title: "Diff Checker for CSV Data", h1: "Diff Checker for CSV Data", metaDescription: "Compare CSV files. Find row changes. Client-side.", keywords: ["csv diff checker", "compare csv", "spreadsheet diff"], intro: "Compare CSV exports to identify data changes.", exampleInput: "Left: id,name\\n1,Alice\\n\\nRight: id,name\\n1,Alice\\n2,Bob", tips: ["Sort by ID first.", "Changed values highlighted.", "Compare migration results."], faqs: [{ q: "Large?", a: "5000 lines." }, { q: "Cell or line?", a: "Line-by-line." }, { q: "Excel?", a: "Export to CSV first." }] },
  { slug: "diff-checker-for-xml-files", ...TOOLS.diff, title: "Diff Checker for XML Files", h1: "Diff Checker for XML Files", metaDescription: "Compare XML documents. Client-side.", keywords: ["xml diff checker", "compare xml"], intro: "Compare XML configs, SOAP messages, and data exports.", exampleInput: "Left: <config><db host=\\\"localhost\\\"/></config>\\nRight: <config><db host=\\\"prod\\\" ssl=\\\"true\\\"/></config>", tips: ["Format XML first.", "Compare SOAP pairs.", "Review pom.xml changes."], faqs: [{ q: "Semantic?", a: "Text-based." }, { q: "Large?", a: "5000 lines." }, { q: "XSLT?", a: "Yes. Compare output." }] },
  { slug: "diff-checker-for-yaml-files", ...TOOLS.diff, title: "Diff Checker for YAML Files", h1: "Diff Checker for YAML Files", metaDescription: "Compare YAML configs. K8s, Docker Compose. Client-side.", keywords: ["yaml diff checker", "compare yaml", "k8s yaml diff"], intro: "YAML is standard for K8s, Docker Compose, and CI. Compare to catch differences.", exampleInput: "Left: image: node:20\\nRight: image: node:22\\ndeploy:\\n  replicas: 3", tips: ["Indentation is structural.", "Compare Compose dev vs prod.", "Review K8s before apply."], faqs: [{ q: "Indentation matters?", a: "Yes. YAML uses it for structure." }, { q: "Helm?", a: "Yes. Standard YAML." }, { q: "Convert?", a: "Use JSON Formatter YAML converter." }] },
  { slug: "diff-checker-for-env-files", ...TOOLS.diff, title: "Diff Checker for .env Files", h1: "Diff Checker for .env Files", metaDescription: "Compare .env files safely. Secrets stay in browser.", keywords: ["env file diff", "compare env", "dotenv diff"], intro: "Missing env vars are a top deployment failure cause.", exampleInput: "Left: DB=localhost\\nDEBUG=true\\n\\nRight: DB=prod\\nDEBUG=false\\nSENTRY=...", tips: ["Sort keys first.", "Check all dev vars exist in prod.", "Watch DEBUG/LOG_LEVEL flags."], faqs: [{ q: "Safe?", a: "Yes. This is why CodeNeat exists." }, { q: "From servers?", a: "SSH, copy, paste." }, { q: ".env.example vs .env?", a: "Great practice." }] },
  { slug: "diff-checker-for-markdown", ...TOOLS.diff, title: "Diff Checker for Markdown", h1: "Diff Checker for Markdown", metaDescription: "Compare Markdown versions. Track docs changes. Client-side.", keywords: ["markdown diff", "compare markdown", "readme diff"], intro: "Track documentation changes and README updates.", exampleInput: "Left: # Project\\nA simple app.\\n\\nRight: # Project\\nA fast app.\\n## License\\nMIT", tips: ["Check no info lost in rewrites.", "Review PR descriptions.", "Check links."], faqs: [{ q: "Renders?", a: "No. Raw source text." }, { q: "Large?", a: "5000 lines." }, { q: "PRs?", a: "Yes. Draft vs final." }] },
  { slug: "diff-checker-for-code-review", ...TOOLS.diff, title: "Diff Checker for Code Review", h1: "Diff Checker for Code Review", metaDescription: "Compare code versions. Any language. Client-side \u2014 source stays private.", keywords: ["code diff checker", "compare code", "code review diff"], intro: "Compare code outside git. Review changes before committing.", exampleInput: "Left: function sum(a,b){return a+b}\\nRight: const sum = (a,b) => a + b;", tips: ["Compare before/after refactoring.", "Review AI code vs yours.", "Compare formatter outputs."], faqs: [{ q: "Syntax highlighting?", a: "Diff colors (green/red/yellow)." }, { q: "Any language?", a: "Yes." }, { q: "Like git diff?", a: "Line-level. git diff --word-diff for more." }] },
];

// ─── JWT Decoder (10 pages) ───
const jwtPages: PseoPage[] = [
  { slug: "jwt-decoder-for-auth0", ...TOOLS.jwt, title: "JWT Decoder for Auth0 Tokens", h1: "JWT Decoder for Auth0", metaDescription: "Decode Auth0 JWT tokens. Inspect claims, scopes, permissions. Client-side.", keywords: ["auth0 jwt decoder", "decode auth0 token", "auth0 claims"], intro: "Auth0 issues JWTs with custom claims. Decode locally to debug auth flows.", exampleInput: "[Paste your Auth0 JWT token here]", tips: ["Check iss matches your domain.", "Verify scopes and permissions.", "Check exp for expiry."], faqs: [{ q: "Safe?", a: "Yes. 100% browser-side." }, { q: "Verify signature?", a: "Needs JWKS public key." }, { q: "Access vs ID?", a: "Access: API scopes. ID: user profile." }] },
  { slug: "jwt-decoder-for-firebase-tokens", ...TOOLS.jwt, title: "JWT Decoder for Firebase Tokens", h1: "JWT Decoder for Firebase", metaDescription: "Decode Firebase Auth tokens. Check claims, email, expiry. Client-side.", keywords: ["firebase jwt decoder", "decode firebase token"], intro: "Firebase tokens contain user identity and custom claims. Decode locally.", exampleInput: "[Paste your Firebase ID token here]", tips: ["Expires after 1 hour.", "sign_in_provider shows auth method.", "Custom claims as top-level keys."], faqs: [{ q: "Expired?", a: "1h TTL. Use getIdToken(true) to refresh." }, { q: "Custom claims?", a: "Set via admin SDK. Top-level payload keys." }, { q: "Admin tokens?", a: "Also JWTs. Same decoding." }] },
  { slug: "jwt-decoder-for-aws-cognito", ...TOOLS.jwt, title: "JWT Decoder for AWS Cognito", h1: "JWT Decoder for AWS Cognito", metaDescription: "Decode Cognito tokens. Groups, attributes. Client-side.", keywords: ["cognito jwt decoder", "decode cognito token"], intro: "Cognito issues ID, access, and refresh tokens. Decode to inspect claims.", exampleInput: "[Paste your Cognito token here]", tips: ["token_use: 'id' or 'access'.", "cognito:groups for memberships.", "iss includes User Pool ID."], faqs: [{ q: "ID vs access?", a: "ID: attributes. Access: scopes." }, { q: "No custom attrs?", a: "Only in ID tokens. custom: prefix." }, { q: "Refresh tokens?", a: "Opaque, not JWTs." }] },
  { slug: "jwt-decoder-for-oauth2-tokens", ...TOOLS.jwt, title: "JWT Decoder for OAuth 2.0 Tokens", h1: "JWT Decoder for OAuth 2.0", metaDescription: "Decode OAuth 2.0 access tokens. Scopes, audience. Client-side.", keywords: ["oauth2 jwt decoder", "decode oauth token", "bearer token decoder"], intro: "OAuth 2.0 tokens contain scopes, audience, and issuer. Decode to debug authorization.", exampleInput: "[Paste your OAuth 2.0 access token here]", tips: ["Check aud matches API.", "scope lists permissions.", "Check exp and iat."], faqs: [{ q: "All OAuth = JWT?", a: "No. Some are opaque tokens." }, { q: "Safe for bearer?", a: "Yes. Never use external decoders." }, { q: "typ: at+jwt?", a: "OAuth 2.0 access token (RFC 9068)." }] },
  { slug: "jwt-decoder-for-openid-connect", ...TOOLS.jwt, title: "JWT Decoder for OpenID Connect", h1: "JWT Decoder for OIDC", metaDescription: "Decode OIDC ID tokens. Identity claims, nonce. Client-side.", keywords: ["oidc jwt decoder", "openid connect token", "decode id token"], intro: "OIDC ID tokens carry identity info. Decode to verify claims and nonce.", exampleInput: "[Paste your OIDC ID token here]", tips: ["Verify nonce for replay protection.", "auth_time shows actual auth time.", "Check email_verified."], faqs: [{ q: "ID vs access?", a: "ID: identity. Access: API permissions." }, { q: "Nonce?", a: "Random string preventing replay attacks." }, { q: "ID tokens for APIs?", a: "No. Use access tokens." }] },
  { slug: "jwt-decoder-for-api-debugging", ...TOOLS.jwt, title: "JWT Decoder for API Debugging", h1: "JWT Decoder for API Debugging", metaDescription: "Debug 401/403 by decoding JWTs. Client-side.", keywords: ["jwt debugging", "api auth debugging", "jwt troubleshoot"], intro: "When your API returns 401/403, decode the JWT to find the problem.", exampleInput: "[Paste JWT from Authorization header]", tips: ["Check exp first (most common).", "Verify aud matches.", "Compare iss with expectations."], faqs: [{ q: "401 steps?", a: "1) expired? 2) audience? 3) issuer? 4) scopes?" }, { q: "Signature invalid?", a: "Wrong key, algorithm, or modified token." }, { q: "From headers?", a: "Copy from Authorization: Bearer." }] },
  { slug: "jwt-decoder-for-keycloak", ...TOOLS.jwt, title: "JWT Decoder for Keycloak", h1: "JWT Decoder for Keycloak", metaDescription: "Decode Keycloak tokens. Realm/client roles. Client-side.", keywords: ["keycloak jwt decoder", "decode keycloak token"], intro: "Keycloak tokens have rich RBAC data. Decode to debug role-based access.", exampleInput: "[Paste your Keycloak token here]", tips: ["realm_access.roles: global. resource_access: per-client.", "Check azp for client used.", "Large tokens from many roles."], faqs: [{ q: "Realm vs client roles?", a: "Realm: global. Client: per-app." }, { q: "Token too large?", a: "Configure role scope mappings." }, { q: "Offline tokens?", a: "JWTs with typ 'Offline'." }] },
  { slug: "jwt-decoder-for-azure-ad", ...TOOLS.jwt, title: "JWT Decoder for Azure AD", h1: "JWT Decoder for Azure AD", metaDescription: "Decode Azure AD / Entra ID tokens. Tenant, roles, groups. Client-side.", keywords: ["azure ad jwt decoder", "microsoft entra token"], intro: "Azure AD tokens have tenant claims, app roles, and group memberships.", exampleInput: "[Paste your Azure AD token here]", tips: ["tid = directory ID.", "oid = user's unique ID.", "roles claim for app roles."], faqs: [{ q: "What is tid?", a: "Tenant ID. Validate against allowed list." }, { q: "Groups as IDs?", a: "Map via Graph API." }, { q: "v1 vs v2?", a: "Different issuer URLs." }] },
  { slug: "jwt-decoder-for-google-identity", ...TOOLS.jwt, title: "JWT Decoder for Google Sign-In", h1: "JWT Decoder for Google Identity", metaDescription: "Decode Google ID tokens. Email, profile, domain. Client-side.", keywords: ["google jwt decoder", "decode google token"], intro: "Google Sign-In tokens contain profile and email data. Decode locally.", exampleInput: "[Paste your Google Sign-In token here]", tips: ["hd = Workspace domain.", "Verify email_verified.", "azp/aud should match client ID."], faqs: [{ q: "What is hd?", a: "Hosted domain. Workspace accounts only." }, { q: "Server validation?", a: "Verify with Google's public keys." }, { q: "Service accounts?", a: "Also JWTs." }] },
  { slug: "jwt-decoder-for-session-management", ...TOOLS.jwt, title: "JWT Decoder for Session Tokens", h1: "JWT Decoder for Sessions", metaDescription: "Decode JWT session tokens. Client-side.", keywords: ["jwt session decoder", "decode session token"], intro: "Many apps use JWTs for stateless sessions. Decode to debug.", exampleInput: "[Paste your session JWT here]", tips: ["Check exp for session lifetime.", "Role and plan info common.", "Compare tokens before/after actions."], faqs: [{ q: "Secure?", a: "Trade-off: stateless but can't revoke individually." }, { q: "Revoke?", a: "Needs server-side blocklist." }, { q: "What data?", a: "User ID, role, minimal permissions." }] },
];

// ─── SQL Formatter (10 pages) ───
const sqlPages: PseoPage[] = [
  { slug: "sql-formatter-for-postgresql", ...TOOLS.sql, title: "SQL Formatter for PostgreSQL", h1: "SQL Formatter for PostgreSQL", metaDescription: "Format PostgreSQL queries. CTEs, window functions, JSONB. Client-side.", keywords: ["postgresql formatter", "format postgres query", "pg sql formatter"], intro: "Format PostgreSQL queries with CTEs, window functions, and JSONB. Your queries stay in your browser.", exampleInput: "WITH active AS (SELECT id, name, COUNT(o.id) as orders FROM users u LEFT JOIN orders o ON u.id = o.user_id WHERE status = 'active' GROUP BY u.id HAVING COUNT(o.id) > 5) SELECT * FROM active ORDER BY orders DESC LIMIT 20;", tips: ["Select PostgreSQL for ::casts and JSONB.", "UPPERCASE keywords.", "Format CTEs separately."], faqs: [{ q: "PG syntax?", a: "Yes. Type casts, JSONB, arrays." }, { q: "PL/pgSQL?", a: "SQL formats. Procedural: basic support." }, { q: "Changes behavior?", a: "No. Whitespace only." }] },
  { slug: "sql-formatter-for-mysql", ...TOOLS.sql, title: "SQL Formatter for MySQL", h1: "SQL Formatter for MySQL", metaDescription: "Format MySQL queries. Backtick identifiers, MySQL functions. Client-side.", keywords: ["mysql formatter", "format mysql query", "mysql beautifier"], intro: "Format MySQL queries with backtick identifiers and GROUP_CONCAT.", exampleInput: "SELECT `u`.`name`, GROUP_CONCAT(DISTINCT `r`.`name`) as roles FROM `users` `u` JOIN `user_roles` `ur` ON `u`.`id` = `ur`.`user_id` WHERE `u`.`active` = 1 LIMIT 50;", tips: ["Select MySQL for backticks.", "LIMIT without OFFSET.", "Consistent backtick quoting."], faqs: [{ q: "Backticks?", a: "Yes. Select MySQL dialect." }, { q: "Stored procs?", a: "Query formats. Bodies: basic support." }, { q: "Safe?", a: "Yes. Browser only." }] },
  { slug: "sql-formatter-for-sqlite", ...TOOLS.sql, title: "SQL Formatter for SQLite", h1: "SQL Formatter for SQLite", metaDescription: "Format SQLite queries and schemas. Client-side.", keywords: ["sqlite formatter", "format sqlite query"], intro: "Format SQLite for mobile apps and embedded systems.", exampleInput: "CREATE TABLE products (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, price REAL); SELECT name, COUNT(*) as ordered FROM products p LEFT JOIN order_items oi ON p.id = oi.product_id GROUP BY p.id;", tips: ["Select SQLite dialect.", "Dynamic typing preserved.", "Format CREATE TABLE clearly."], faqs: [{ q: "SQLite syntax?", a: "Yes. AUTOINCREMENT, date functions." }, { q: ".dump?", a: "Yes. All DDL/DML." }, { q: "CTEs?", a: "Yes, since 3.8.3." }] },
  { slug: "sql-formatter-for-tsql-server", ...TOOLS.sql, title: "SQL Formatter for T-SQL", h1: "SQL Formatter for T-SQL", metaDescription: "Format T-SQL. TOP, NOLOCK, CROSS APPLY. Client-side.", keywords: ["tsql formatter", "sql server formatter", "mssql beautifier"], intro: "T-SQL includes TOP, NOLOCK hints, and square bracket identifiers.", exampleInput: "SELECT TOP 100 [u].[Name], (SELECT COUNT(*) FROM [Orders] o WITH (NOLOCK) WHERE o.[UserId] = u.[Id]) as Orders FROM [Users] [u] WHERE [u].[IsActive] = 1 ORDER BY Orders DESC;", tips: ["Select T-SQL dialect.", "GETDATE() and DATEADD.", "Format stored procs."], faqs: [{ q: "T-SQL syntax?", a: "TOP, NOLOCK, CROSS APPLY, square brackets." }, { q: "TRY/CATCH?", a: "Basic support." }, { q: "CTEs?", a: "Yes." }] },
  { slug: "sql-formatter-for-oracle-plsql", ...TOOLS.sql, title: "SQL Formatter for Oracle PL/SQL", h1: "SQL Formatter for Oracle PL/SQL", metaDescription: "Format Oracle SQL. ROWNUM, CONNECT BY, DECODE. Client-side.", keywords: ["oracle sql formatter", "plsql formatter", "oracle beautifier"], intro: "Oracle SQL includes ROWNUM, DECODE, and hierarchical queries.", exampleInput: "SELECT name, DECODE(status, 'A', 'Active', 'I', 'Inactive') as status_text, ROW_NUMBER() OVER (PARTITION BY dept_id ORDER BY salary DESC) as rank FROM employees WHERE ROWNUM <= 1000;", tips: ["Select PL/SQL for DECODE, NVL, TO_DATE.", "ROWNUM for row limiting.", "Format packages clearly."], faqs: [{ q: "Oracle functions?", a: "Yes. DECODE, NVL, CONNECT BY." }, { q: "PL/SQL blocks?", a: "SQL formats. BEGIN/END: basic support." }, { q: "FETCH FIRST?", a: "Yes. Oracle 12c+." }] },
  { slug: "sql-formatter-for-bigquery", ...TOOLS.sql, title: "SQL Formatter for BigQuery", h1: "SQL Formatter for BigQuery", metaDescription: "Format BigQuery SQL. STRUCT, ARRAY, UNNEST. Client-side.", keywords: ["bigquery formatter", "format bigquery sql", "bq formatter"], intro: "BigQuery includes STRUCT, ARRAY, and wildcard tables.", exampleInput: "SELECT user_id, ARRAY_AGG(STRUCT(event_name, timestamp)) as events, COUNT(DISTINCT session_id) as sessions FROM `project.analytics.events_*` WHERE _TABLE_SUFFIX BETWEEN '20260401' AND '20260413' GROUP BY user_id LIMIT 1000;", tips: ["Backtick project.dataset.table preserved.", "Format CTEs for analytics.", "UPPERCASE keywords."], faqs: [{ q: "BQ syntax?", a: "STRUCT, ARRAY_AGG, UNNEST, wildcards." }, { q: "Scripting?", a: "SQL formats. Variables: basic support." }, { q: "Safe?", a: "Yes. Queries stay in browser." }] },
  { slug: "sql-formatter-for-stored-procedures", ...TOOLS.sql, title: "SQL Formatter for Stored Procedures", h1: "SQL Formatter for Stored Procedures", metaDescription: "Format stored procedure SQL. Client-side.", keywords: ["stored procedure formatter", "format sp", "procedure beautifier"], intro: "Format to separate SQL from procedural logic.", exampleInput: "CREATE OR REPLACE PROCEDURE update_stats(p_user_id INT) LANGUAGE SQL AS $$ UPDATE stats SET count = (SELECT COUNT(*) FROM logs WHERE user_id = p_user_id) WHERE user_id = p_user_id; $$;", tips: ["Format SQL inside separately.", "Indent parameters.", "Separate declarations from queries."], faqs: [{ q: "Procedural logic?", a: "SQL formats. IF/LOOP: basic." }, { q: "Triggers?", a: "Yes." }, { q: "All databases?", a: "Select dialect." }] },
  { slug: "sql-formatter-for-complex-joins", ...TOOLS.sql, title: "SQL Formatter for Complex Joins", h1: "SQL Formatter for Complex Joins", metaDescription: "Format multi-JOIN queries. See relationships. Client-side.", keywords: ["sql join formatter", "complex join formatter"], intro: "Multi-JOIN queries on one line are unreadable. Format to show relationships.", exampleInput: "SELECT c.name, p.product FROM customers c INNER JOIN orders o ON c.id = o.customer_id INNER JOIN order_items oi ON o.id = oi.order_id INNER JOIN products p ON oi.product_id = p.id LEFT JOIN shippers s ON o.shipper_id = s.id WHERE o.date > '2026-01-01';", tips: ["Each JOIN on its own line.", "Short meaningful aliases.", "Most selective JOINs first."], faqs: [{ q: "Affects order?", a: "No. Optimizer decides." }, { q: "How many?", a: "No limit." }, { q: "Self-joins?", a: "Same formatting." }] },
  { slug: "sql-formatter-for-subqueries", ...TOOLS.sql, title: "SQL Formatter for Subqueries", h1: "SQL Formatter for Subqueries", metaDescription: "Format nested subqueries with clear indentation. Client-side.", keywords: ["subquery formatter", "nested query formatter"], intro: "Deeply nested subqueries need indentation to show hierarchy.", exampleInput: "SELECT name FROM users WHERE id IN (SELECT user_id FROM orders WHERE total > (SELECT AVG(total) FROM orders)) ORDER BY name;", tips: ["Each level indents more.", "Consider CTEs instead.", "Format innermost first."], faqs: [{ q: "CTEs better?", a: "Usually more readable." }, { q: "Max depth?", a: "10+ but refactor if >3-4." }, { q: "Performance?", a: "Formatting doesn't affect it." }] },
  { slug: "sql-formatter-for-data-migration", ...TOOLS.sql, title: "SQL Formatter for Data Migration", h1: "SQL Formatter for Migration Scripts", metaDescription: "Format migration scripts. ALTER TABLE, INSERT. Client-side \u2014 schema stays private.", keywords: ["migration formatter", "alter table formatter", "schema migration sql"], intro: "Format migration scripts for review before running against production.", exampleInput: "ALTER TABLE users ADD COLUMN dept_id INTEGER REFERENCES departments(id); CREATE INDEX idx_dept ON users(dept_id); UPDATE users SET dept_id = 1 WHERE role LIKE '%eng%';", tips: ["Catch missing WHERE clauses.", "Separate DDL from DML.", "Include rollback statements."], faqs: [{ q: "Safe?", a: "Yes. Schema stays in browser." }, { q: "Affects execution?", a: "No. Whitespace only." }, { q: "Multiple statements?", a: "Yes. Semicolon-separated." }] },
];

// ─── Hash Generator (10 pages) ───
const hashPages: PseoPage[] = [
  { slug: "md5-hash-generator-online", ...TOOLS.hash, title: "MD5 Hash Generator Online", h1: "MD5 Hash Generator", metaDescription: "Generate MD5 hashes. Checksums and integrity. 100% client-side.", keywords: ["md5 hash generator", "md5 checksum", "generate md5"], intro: "MD5 produces a 128-bit (32 hex) hash for checksums and data integrity.", exampleInput: "Hello, World!", tips: ["Not for security (collisions).", "Good for checksums, cache keys.", "32-char hex output."], faqs: [{ q: "Secure?", a: "No. Use SHA-256 for security." }, { q: "When use?", a: "Checksums, cache keys, dedup." }, { q: "Safe?", a: "Yes. Browser only." }] },
  { slug: "sha256-hash-generator", ...TOOLS.hash, title: "SHA-256 Hash Generator", h1: "SHA-256 Hash Generator", metaDescription: "Generate SHA-256 hashes. Industry standard. Client-side.", keywords: ["sha256 generator", "sha-256 calculator", "secure hash"], intro: "SHA-256 is the standard for secure hashing. 256-bit (64 hex) output.", exampleInput: "The quick brown fox jumps over the lazy dog", tips: ["Used by Bitcoin and Git.", "Compare with published checksums.", "WebCrypto for performance."], faqs: [{ q: "Secure?", a: "Yes. No practical attacks." }, { q: "vs SHA-512?", a: "Both secure. SHA-512 faster on 64-bit." }, { q: "Verify downloads?", a: "Compare hash with publisher's checksum." }] },
  { slug: "hash-generator-for-file-integrity", ...TOOLS.hash, title: "Hash Generator for File Integrity", h1: "Hash Generator for File Integrity", metaDescription: "Generate file hashes. Verify downloads. Client-side.", keywords: ["file hash generator", "checksum generator", "verify file hash"], intro: "Verify downloaded files with hash comparison.", exampleInput: "[Upload a file to generate all hash types]", tips: ["Verify security-critical downloads.", "SHA-256 most common.", "Files hashed locally."], faqs: [{ q: "How to verify?", a: "Upload, compare hash with publisher's." }, { q: "Which algorithm?", a: "Whatever publisher provides." }, { q: "File uploaded?", a: "No. Hashed locally." }] },
  { slug: "hash-generator-for-password-hashing", ...TOOLS.hash, title: "Hash Generator for Passwords", h1: "Hash Generator for Password Hashing", metaDescription: "Generate password hashes. Learn hashing concepts. Client-side.", keywords: ["password hash generator", "hash password online"], intro: "Understand password hashing. Production: use bcrypt/Argon2, not plain SHA.", exampleInput: "MySecurePassword!", tips: ["Never plain SHA in production.", "Educational: see deterministic output.", "Avalanche effect: tiny change = different hash."], faqs: [{ q: "SHA for passwords?", a: "No. Use bcrypt/Argon2id with salt." }, { q: "Same hash?", a: "Yes. Deterministic. That's why salting needed." }, { q: "Safe here?", a: "Yes. Browser-only." }] },
  { slug: "hash-generator-for-checksums", ...TOOLS.hash, title: "Hash Generator for Checksums", h1: "Hash Generator for Checksums", metaDescription: "Generate checksums. Verify data integrity. Client-side.", keywords: ["checksum generator", "data integrity checksum"], intro: "Checksums verify data hasn't been corrupted during transfer.", exampleInput: "order_id=12345&amount=99.99&currency=USD", tips: ["Share alongside data.", "Detect unauthorized changes.", "Compare before/after transfer."], faqs: [{ q: "What is checksum?", a: "Fingerprint from data. Any change = different checksum." }, { q: "Which algorithm?", a: "MD5 for speed. SHA-256 for security." }, { q: "Large files?", a: "Yes. WebCrypto handles locally." }] },
  { slug: "hash-generator-for-api-signatures", ...TOOLS.hash, title: "Hash Generator for API Signatures", h1: "Hash Generator for API Signatures", metaDescription: "Generate hashes for API signing. Client-side.", keywords: ["api signature hash", "hmac generator", "webhook signature"], intro: "Many APIs use hash signatures. Generate hashes to test implementations.", exampleInput: "payload={\"event\":\"payment.completed\"}&secret=test_secret", tips: ["API signatures use HMAC-SHA256.", "Webhook signatures verify authenticity.", "Compare computed vs header."], faqs: [{ q: "What is HMAC?", a: "Hash + secret key = integrity + authenticity." }, { q: "Webhooks?", a: "Sender HMACs payload, receiver verifies." }, { q: "Generate HMAC?", a: "Standard hashes only. HMAC needs implementation." }] },
  { slug: "sha512-hash-generator", ...TOOLS.hash, title: "SHA-512 Hash Generator", h1: "SHA-512 Hash Generator", metaDescription: "Generate SHA-512 hashes. Fast on 64-bit. Client-side.", keywords: ["sha512 generator", "sha-512 calculator"], intro: "SHA-512 produces 512-bit (128 hex) hash. Faster than SHA-256 on 64-bit systems.", exampleInput: "Data requiring strong hash digest", tips: ["Faster on 64-bit processors.", "Larger output space.", "Use when protocol requires."], faqs: [{ q: "More secure?", a: "Both secure. Theoretical difference." }, { q: "When use?", a: "64-bit systems, protocol requirements." }, { q: "Performance?", a: "Up to 50% faster on 64-bit." }] },
  { slug: "hash-generator-for-blockchain", ...TOOLS.hash, title: "Hash Generator for Blockchain", h1: "Hash Generator for Blockchain", metaDescription: "Generate SHA-256 hashes. Understand proof-of-work. Client-side.", keywords: ["blockchain hash", "bitcoin hash", "proof of work"], intro: "Blockchain uses SHA-256 for block hashing and proof-of-work.", exampleInput: "Block #12345 | Prev: 0000abc...def | Nonce: 42 | Tx: [tx1, tx2]", tips: ["Miners try nonces until hash has enough zeros.", "One char change = completely different hash.", "Bitcoin uses double SHA-256."], faqs: [{ q: "How blockchain hashes?", a: "Each block has previous block's hash. Tamper-evident chain." }, { q: "Proof-of-work?", a: "Finding nonce that produces hash with required zeros." }, { q: "Mine Bitcoin?", a: "No. Requires ASIC hardware." }] },
  { slug: "hash-generator-for-data-deduplication", ...TOOLS.hash, title: "Hash Generator for Deduplication", h1: "Hash Generator for Deduplication", metaDescription: "Generate content hashes for duplicate detection. Client-side.", keywords: ["deduplication hash", "duplicate detection", "content fingerprint"], intro: "Hash-based deduplication identifies identical content without byte-by-byte comparison.", exampleInput: "Content block to deduplicate: This paragraph may appear in multiple documents.", tips: ["Hash content, check if hash exists.", "MD5 for speed, SHA-256 for safety.", "Block-level dedup with chunking."], faqs: [{ q: "How?", a: "Hash each block. Existing hash = duplicate." }, { q: "Collisions?", a: "SHA-256: astronomically unlikely." }, { q: "Algorithm?", a: "SHA-256 for security. MD5 for performance." }] },
  { slug: "hash-generator-for-cache-keys", ...TOOLS.hash, title: "Hash Generator for Cache Keys", h1: "Hash Generator for Cache Keys", metaDescription: "Generate hash-based cache keys. Unique identifiers. Client-side.", keywords: ["cache key hash", "hash cache key", "unique cache key"], intro: "Caching systems use hashes to map requests to cached responses.", exampleInput: "{\"endpoint\":\"/api/users\",\"params\":{\"page\":1,\"sort\":\"name\"}}", tips: ["Hash full request signature.", "Sort params before hashing.", "MD5 sufficient for cache keys."], faqs: [{ q: "Why hash?", a: "Fixed-length keys from variable inputs." }, { q: "MD5 or SHA-256?", a: "MD5. Collision = cache miss, not security issue." }, { q: "Param order?", a: "Sort alphabetically first." }] },
];

// ─── Comparison Pages ───
const comparisonPages: ComparisonPage[] = [
  {
    slug: "codeneat-vs-codebeautify",
    title: "CodeNeat vs CodeBeautify \u2014 Privacy-First Alternative",
    h1: "CodeNeat vs CodeBeautify",
    metaDescription: "Compare CodeNeat and CodeBeautify. Client-side vs server-side processing for your code.",
    keywords: ["codeneat vs codebeautify", "codebeautify alternative", "privacy developer tools"],
    intro: "CodeBeautify has 23M+ monthly visits. The critical difference is how they handle your data.",
    sections: [
      { heading: "How They Handle Your Data", content: "CodeBeautify processes input on their servers. Your code is sent via HTTP.\n\nCodeNeat processes everything in your browser. Open DevTools: zero data requests." },
      { heading: "Feature Comparison", content: "| Feature | CodeNeat | CodeBeautify |\n|---|---|---|\n| Processing | Client-side | Server-side |\n| Privacy | Data stays in browser | Sent to servers |\n| Offline | Yes | No |\n| Open source | Yes (MIT) | No |\n| Ads | Minimal | Heavy |\n| Tools | 8 deep | 50+ broad |" },
      { heading: "When to Choose CodeNeat", content: "When working with sensitive data: API configs, database queries, JWT tokens, proprietary code." },
      { heading: "When CodeBeautify Works", content: "50+ tools for niche formats. If data is not sensitive, breadth is the advantage." },
      { heading: "Privacy Matters", content: "Developers paste credentials and tokens daily. CodeNeat eliminates the risk: no server, no logs, no leaks." },
    ],
    faqs: [
      { q: "Really client-side?", a: "Yes. DevTools Network tab: zero data requests." },
      { q: "As many tools?", a: "No. 8 deep tools vs 50+ shallow." },
      { q: "Open source?", a: "Yes. GitHub MIT license." },
    ],
  },
  {
    slug: "best-free-developer-tools-online-2026",
    title: "Best Free Developer Tools Online 2026",
    h1: "Best Free Developer Tools Online (2026)",
    metaDescription: "Best free online dev tools in 2026. JSON formatters, regex testers, diff checkers \u2014 with privacy ratings.",
    keywords: ["best developer tools 2026", "free online dev tools", "best json formatter"],
    intro: "This guide covers the best online developer tools in 2026, with a focus on functionality and privacy.",
    sections: [
      { heading: "JSON Formatters", content: "**CodeNeat** \u2014 Client-side, tree view, JSON Path. Best for sensitive data.\n**jsonformatter.org** \u2014 Established. Server-side.\n**jsonlint.com** \u2014 Validation focused. Server-side." },
      { heading: "Regex Testers", content: "**CodeNeat** \u2014 Client-side matching. Safe for real data.\n**regex101.com** \u2014 Feature-rich. Server-side.\nChoose CodeNeat for production data." },
      { heading: "SQL Formatters", content: "**CodeNeat** \u2014 Multi-dialect. Client-side.\nSQL queries reveal schema and logic \u2014 use client-side." },
      { heading: "JWT Decoders", content: "**CodeNeat** \u2014 100% client-side.\n**jwt.io** \u2014 Well-known. Local processing + analytics.\nNever paste production tokens into server-side decoders." },
      { heading: "The Privacy Factor", content: "For sensitive data, prefer client-side. CodeNeat: 8 tools, zero server communication." },
    ],
    faqs: [
      { q: "Which site?", a: "Client-side for sensitive data. Any for learning." },
      { q: "Client-side fast?", a: "Usually faster \u2014 no network round-trip." },
      { q: "How to verify?", a: "DevTools Network tab. Zero data requests = client-side." },
    ],
  },
];

// ─── Exports ───
const allPseoPages: PseoPage[] = [
  ...jsonPages, ...base64Pages, ...urlPages, ...regexPages,
  ...diffPages, ...jwtPages, ...sqlPages, ...hashPages,
];

export function getAllPseoPages(): PseoPage[] { return allPseoPages; }
export function getPseoPage(slug: string): PseoPage | undefined { return allPseoPages.find((p) => p.slug === slug); }
export function getComparisonPages(): ComparisonPage[] { return comparisonPages; }
export function getComparisonPage(slug: string): ComparisonPage | undefined { return comparisonPages.find((p) => p.slug === slug); }
export function getAllSlugs(): string[] { return [...allPseoPages.map((p) => p.slug), ...comparisonPages.map((p) => p.slug)]; }
